name: Lint Style

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 18
          distribution: 'temurin'
      
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Install linter
        run: |
          wget https://raw.githubusercontent.com/checkstyle/checkstyle/master/scripts/installCheckstyle.sh
          source installCheckstyle.sh
          mvn install:checkstyle -o
      - name: Install PMD
        run: |
          wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.50.0/pmd-bin-6.50.0.zip
          unzip pmd-bin-6.50.0.zip
          export PATH=$PATH:$PWD/pmd-bin-6.50.0/bin

      - name: Run PMD
        run: |
          mvn pmd:check

      - name: Install SpotBugs
        run: |
          wget https://repo.maven.apache.org/maven2/com/github/spotbugs/spotbugs-maven-plugin/4.6.2/spotbugs-maven-plugin-4.6.2.jar
          mv spotbugs-maven-plugin-4.6.2.jar $HOME/.m2/repository/com/github/spotbugs/spotbugs-maven-plugin/4.6.2/
      
      - name: Run SpotBugs
        run: |
          mvn spotbugs:check
